### ISSUE TITLE
Split networking and storage

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/probert#70]
From https://bugs.launchpad.net/ubuntu/+source/probert/+bug/1834897, probert should be split into networking and storage parts, to make it better to have consoleconf require just the bits it needs:

> consoleconf depends on probert via subiquitycore dependency.
> 
> consoleconf has networking ui.
> 
> consoleconf does not have disk partitioning ui.
> 
> therefore consoleconf needs/wants all the "networking" things (for netplan, resolveconf, bonds, vlans, etc) but none of the "storage" things (i.e. mdadm, lvm2, etc).
> 
> Please consider splitting probert dependencies into metapackages for "networking" and "storage" things.

**Comment by xnox** [comment]
fix released.
